### ISSUE TITLE
Python wrapping using SWIG

### ISSUE THREAD

**Issue by dneise** [cherenkov-plenoscope/merlict_development_kit#34]
I just wanted to report ... I am currently trying to generate python wrappers for this using SWIG. 
It works ... a bit. I am currently trying to recreate this unit test here, using the wrapped python interface.

https://github.com/cherenkov-plenoscope/merlict_development_kit/blob/770cd2769c5a36585a498ec2ee1ae5eb2dd17cb9/merlict/tests/PhotonTest.cpp#L84

Currently it does not work, since I have problems wrapping a `std::vector<ml::Photon>`. The wrapped C++ code throws a compile error: 
```
/usr/include/c++/7/bits/stl_construct.h:75:7: error: no matching function for call to ‘merlict::Photon::Photon()’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from example_wrap.cpp:3238:0:
merlict.h:656:5: note: candidate: merlict::Photon::Photon(merlict::Vec3, merlict::Vec3, double)
     Photon(
     ^~~~~~
merlict.h:656:5: note:   candidate expects 3 arguments, 0 provided
```

So it seems it would help if `Photon` had a default ctor. And I believe I've read somewhere (back when I was still sometimes looking at C++ ... that it using custom classes in STL containers is *easier* if they fulfill a set of features ... I think it was something like, they should have:
 - default ctor
 - assignment operator
 - (... not sure what else ...)

I think I will give `Photon` a default ctor now and see what happens...

**Comment by relleums** [comment]
Well, as long as the tests pass it should be fine. Although I wonder why these ctors are suddenly needed. I assume SWIG want to provide a functionality which is not used in merlict.

**Comment by dneise** [comment]
Yes, I think you are right. 
When one exposes a vector of a custom class, then it is in principle possible to create a `vector<Photons>` of lenth 1000. And then these 1000 photons needed to be created somehow.

But as long as this is never done ...

**Comment by dneise** [comment]
Okay so for the moment, we gave `Photon` and `RayForPropagation` default c-tors. This can be seen in PR #37. It seems to work.

So this issue can be closed for now.
