### ISSUE TITLE
cmake and "one_source" build?

### ISSUE THREAD

**Issue by dneise** [cherenkov-plenoscope/merlict_development_kit#40]
The cmake build takes quite some time on travis .... should we do both, or should we only do the "one_source" build?

**Comment by mahnen** [comment]
I think it would be good to have both. One could ship the merlict.h/merlict.cpp and tell people to use it as the library. Furthermore, the merlict applications could be built using this library and CMAKE (in particular on travis; the python library together with the tests && execute).

**Comment by dneise** [comment]
ok. thanks.

closing this, since question is answered.
